# Generated by Django 4.0.5 on 2022-07-12 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auction_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='top_bid',
            field=models.ForeignKey(blank=True, default=models.DecimalField(decimal_places=2, max_digits=10), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_top_bid', to='auctions.bid'),
        ),
    ]
